version: "3.6"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9999:80"
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./code:/var/www/html
    restart: always
    depends_on:
      - php
  php:
    build: dockers/phalcon
    image: phalcon-application
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./code:/var/www/html
